name: Snake

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-22.04
    steps:
      - uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
      - run: cp -a dist/github-snake.svg .
      - run: git check out -b "Tmp"
      - run: git add . 
      - run: git commit -m "Tmp" 
      - run: git push --set-upstream origin Tmp

  
